# Generated by Django 4.0.10 on 2023-11-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('moon_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('moon_name', models.CharField(max_length=150)),
                ('moon_system_id', models.BigIntegerField()),
                ('moon_system_name', models.CharField(max_length=150)),
                ('moon_constellation_id', models.BigIntegerField()),
                ('moon_constellation_name', models.CharField(max_length=150)),
                ('moon_region_id', models.BigIntegerField()),
                ('moon_region_name', models.CharField(max_length=150)),
                ('moon_r_rating', models.IntegerField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MoonOres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.BigIntegerField()),
                ('type_name', models.CharField(max_length=150)),
                ('distribution', models.FloatField()),
                ('volume', models.FloatField()),
                ('portion_size', models.FloatField()),
                ('extraction_per_hour_m3', models.FloatField()),
                ('units_per_hour', models.FloatField()),
                ('moon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moonimport.moon')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
